#!/bin/sh

set -e

cd ${AUTOPKGTEST_TMP}
for p in $(py3versions -s); do
    $p -c "import slapdtest; server = slapdtest.SlapdObject(); server.start(); assert server.port > 0 and server.port < 65536; server.stop()"
done
